definitions:
  authcontroller.ChangePassword.Req:
    properties:
      newPass:
        type: string
      oldPass:
        type: string
    required:
    - newPass
    - oldPass
    type: object
  authucase.ConfirmForgotPasswordIn:
    properties:
      code:
        type: string
      email:
        type: string
      newPass:
        type: string
    required:
    - code
    - email
    - newPass
    type: object
  authucase.ConfirmSignUpIn:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
  authucase.ForgotPasswordIn:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  authucase.LoginIn:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  authucase.LoginOut:
    properties:
      accessToken:
        type: string
      idToken:
        type: string
      refreshToken:
        type: string
    type: object
  authucase.RefreshTokenIn:
    properties:
      email:
        type: string
      refreshToken:
        type: string
    required:
    - email
    - refreshToken
    type: object
  authucase.RefreshTokenOut:
    properties:
      accessToken:
        type: string
      idToken:
        type: string
      refreshToken:
        type: string
    type: object
  authucase.ResendConfirmationCodeIn:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  authucase.SetNewPasswordIn:
    properties:
      email:
        type: string
      newPass:
        type: string
      oldPass:
        type: string
    required:
    - email
    - newPass
    - oldPass
    type: object
  authucase.SignUpIn:
    properties:
      email:
        type: string
      nickName:
        type: string
      password:
        type: string
    required:
    - email
    - nickName
    - password
    type: object
  er.APIError:
    properties:
      code:
        type: string
      msg:
        type: string
      traceID:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/change-password:
    post:
      parameters:
      - description: req
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authcontroller.ChangePassword.Req'
      responses:
        "200":
          description: OK
      tags:
      - auth
  /v1/confirm-forgot-password:
    post:
      parameters:
      - description: Request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.ConfirmForgotPasswordIn'
      responses:
        "200":
          description: OK
      tags:
      - auth
  /v1/confirm-sign-up:
    post:
      parameters:
      - description: Request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.ConfirmSignUpIn'
      responses:
        "200":
          description: OK
      tags:
      - auth
  /v1/forgot-password:
    post:
      parameters:
      - description: Request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.ForgotPasswordIn'
      responses:
        "200":
          description: OK
      tags:
      - auth
  /v1/healthy:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/er.APIError'
      tags:
      - general
  /v1/invite-user:
    post:
      parameters:
      - description: request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.LoginIn'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authucase.LoginOut'
      tags:
      - auth
  /v1/login:
    post:
      parameters:
      - description: request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.LoginIn'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authucase.LoginOut'
      tags:
      - auth
  /v1/ping:
    get:
      responses:
        "200":
          description: OK
      tags:
      - general
  /v1/refresh-token:
    post:
      parameters:
      - description: req
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.RefreshTokenIn'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authucase.RefreshTokenOut'
      tags:
      - auth
  /v1/resend-confirmation-code:
    post:
      parameters:
      - description: request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.ResendConfirmationCodeIn'
      responses:
        "200":
          description: OK
      tags:
      - auth
  /v1/set-new-password:
    post:
      parameters:
      - description: request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.SetNewPasswordIn'
      responses:
        "200":
          description: OK
      tags:
      - auth
  /v1/sign-up:
    post:
      parameters:
      - description: req
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.SignUpIn'
      responses:
        "200":
          description: OK
      tags:
      - auth
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
