definitions:
  authucase.ConfirmForgotPasswordIn:
    properties:
      code:
        type: string
      email:
        type: string
      newPass:
        type: string
    required:
    - code
    - email
    - newPass
    type: object
  authucase.ConfirmSignUpIn:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
  authucase.ForgotPasswordIn:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  authucase.LoginIn:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  authucase.LoginOut:
    properties:
      accessToken:
        type: string
      idToken:
        type: string
      refreshToken:
        type: string
    type: object
  authucase.RefreshTokenIn:
    properties:
      email:
        type: string
      refreshToken:
        type: string
    required:
    - email
    - refreshToken
    type: object
  authucase.RefreshTokenOut:
    properties:
      accessToken:
        type: string
      idToken:
        type: string
      refreshToken:
        type: string
    type: object
  authucase.SignUpIn:
    properties:
      email:
        type: string
      nickName:
        type: string
      password:
        type: string
    required:
    - email
    - nickName
    - password
    type: object
  er.APIError:
    properties:
      code:
        type: string
      msg:
        type: string
      traceID:
        type: string
    type: object
info:
  contact: {}
paths:
  /healthy:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/er.APIError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/er.APIError'
  /login:
    post:
      parameters:
      - description: request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.LoginIn'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authucase.LoginOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APIError'
      tags:
      - auth
  /ping:
    get:
      responses:
        "200":
          description: OK
      tags:
      - TroubleShooting
  /v1/confirm-sign-up:
    post:
      parameters:
      - description: Request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.ConfirmSignUpIn'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APIError'
      tags:
      - auth
  /v1/forgotPassword:
    post:
      parameters:
      - description: Request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.ForgotPasswordIn'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/er.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APIError'
      tags:
      - Home
  /v1/refresh-token:
    post:
      parameters:
      - description: req
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.RefreshTokenIn'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authucase.RefreshTokenOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APIError'
      tags:
      - auth
  /v1/sign-up:
    post:
      parameters:
      - description: req
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authucase.SignUpIn'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/er.APIError'
      tags:
      - auth
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
