definitions:
  dm.ErrResp:
    properties:
      error:
        type: string
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /healthy:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dm.ErrResp'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/dm.ErrResp'
      summary: Check the server healthy
  /ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dm.ErrResp'
      summary: Check the server started
swagger: "2.0"
