definitions:
  authcontroller.ForgotPassword.Req:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  authcontroller.Login.Req:
    properties:
      Name:
        type: string
      Password:
        type: string
    required:
    - Name
    - Password
    type: object
  authcontroller.Register.Req:
    properties:
      email:
        type: string
      nickName:
        type: string
    required:
    - email
    - nickName
    type: object
  authucase.LoginOut:
    properties:
      accessToken:
        type: string
      idToken:
        type: string
      refreshToken:
        type: string
    type: object
  er.APIError:
    properties:
      code:
        type: string
      msg:
        type: string
      traceID:
        type: string
    type: object
info:
  contact: {}
paths:
  /Register:
    post:
      parameters:
      - description: Register User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authcontroller.Register.Req'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APIError'
        "500":
          description: Internal Server Error
          schema:
            type: string
  /healthy:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/er.APIError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/er.APIError'
  /login:
    post:
      parameters:
      - description: Login User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authcontroller.Login.Req'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/authucase.LoginOut'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APIError'
        "500":
          description: Internal Server Error
          schema:
            type: string
  /ping:
    get:
      responses:
        "200":
          description: OK
      tags:
      - TroubleShooting
  /v1/forgotPassword:
    post:
      parameters:
      - description: Request body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/authcontroller.ForgotPassword.Req'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/er.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/er.APIError'
        "500":
          description: Internal Server Error
          schema:
            type: string
      tags:
      - Home
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
