// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/skyrocketOoO/serverx/internal/controller/auth"
	auth2 "github.com/skyrocketOoO/serverx/internal/usecase/auth"
)

// Injectors from injector.go:

func NewHandler() *auth.Handler {
	usecase := auth2.NewUsecase()
	handler := auth.NewHandler(usecase)
	return handler
}
