// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/skyrocketOoO/serverx/internal/controller/auth"
	"github.com/skyrocketOoO/serverx/internal/service/cognito"
	auth2 "github.com/skyrocketOoO/serverx/internal/usecase/auth"
)

// Injectors from injector.go:

func NewHandler() (*auth.Handler, error) {
	client, err := cognito.New()
	if err != nil {
		return nil, err
	}
	usecase := auth2.NewUsecase(client)
	handler := auth.NewHandler(usecase)
	return handler, nil
}
