// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/skyrocketOoO/serverx/internal/controller"
	auth2 "github.com/skyrocketOoO/serverx/internal/controller/auth"
	general2 "github.com/skyrocketOoO/serverx/internal/controller/general"
	"github.com/skyrocketOoO/serverx/internal/service/cognito"
	"github.com/skyrocketOoO/serverx/internal/usecase/auth"
	"github.com/skyrocketOoO/serverx/internal/usecase/general"
)

// Injectors from injector.go:

func NewHandler() (*controller.Handler, error) {
	client, err := cognito.New()
	if err != nil {
		return nil, err
	}
	usecase := auth.NewUsecase(client)
	handler := auth2.NewHandler(usecase)
	generalUsecase := general.NewUsecase()
	generalHandler := general2.NewHandler(generalUsecase)
	controllerHandler := controller.NewHandler(handler, generalHandler)
	return controllerHandler, nil
}
